import { all, takeEvery } from "redux-saga/effects";
import {
  getProductSaga,
  createProductSaga,
  updateProductSaga,
  deleteProductSaga,
  getCartSaga,
  createCartSaga,
  updateCartSaga,
  deleteCartSaga,
  loginSaga,
  logoutSaga,
  createOrderSaga,
  getDataOrderSaga,
  deleteOrderSaga,
  updateOrderSaga,
  createUserSaga,
  updateUserSaga,
  getUserSaga,
} from "~/pages/saga/saga";
import {
  GET_PRODUCT,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  GET_CART,
  CREATE_CART,
  UPDATE_CART,
  DELETE_CART,
  LOGIN,
  LOGOUT,
  ADD_ORDER,
  GET_DATA_ORDER,
  DELETE_ORDER,
  UPDATE_ORDER,
  CREATE_USER,
  UPDATE_USER,
  GET_USER,
} from "~/constants";
export default function* rootSaga() {
  yield all([
    takeEvery(GET_PRODUCT, getProductSaga),
    takeEvery(CREATE_PRODUCT, createProductSaga),
    takeEvery(UPDATE_PRODUCT, updateProductSaga),
    takeEvery(DELETE_PRODUCT, deleteProductSaga),
    takeEvery(GET_CART, getCartSaga),
    takeEvery(CREATE_CART, createCartSaga),
    takeEvery(UPDATE_CART, updateCartSaga),
    takeEvery(DELETE_CART, deleteCartSaga),
    takeEvery(LOGIN, loginSaga),
    takeEvery(LOGOUT, logoutSaga),
    takeEvery(ADD_ORDER, createOrderSaga),
    takeEvery(GET_DATA_ORDER, getDataOrderSaga),
    takeEvery(DELETE_ORDER, deleteOrderSaga),
    takeEvery(UPDATE_ORDER, updateOrderSaga),
    takeEvery(CREATE_USER, createUserSaga),
    takeEvery(UPDATE_USER, updateUserSaga),
    takeEvery(GET_USER, getUserSaga),
  ]);
}
